table 'Spotify Songs'
	lineageTag: ba5fa160-42ff-4aee-afc6-8bed4ab749d2

	measure '% of Total Streams' =
			
			VAR m1 =
			SUM(
			    'Spotify Songs'[Streams]
			)
			
			VAR m2 =
			CALCULATE(
			    SUM('Spotify Songs'[Streams]),
			    ALL(
			        'Spotify Songs'[Track Name]
			    )
			)
			
			RETURN
			DIVIDE(
			    m1,
			    m2,
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c11c733f-800f-4f22-b028-dc83b15a9f4d

	measure 'Select Track Name' =
			
			IF(
			    COUNT( 'Spotify Songs'[Track Name] ) = CALCULATE( DISTINCTCOUNT('Spotify Songs'[Track Name]), ALL('Spotify Songs'[Track Name]) ),
			    "-",
			    SELECTEDVALUE( 'Spotify Songs'[Track Name] )
			)
		lineageTag: 798ccb1d-fea3-43d6-ade3-94fa64bcfb57

	measure 'Select Artist Name' =
			
			IF(
			    COUNT( 'Spotify Songs'[Track Name] ) = CALCULATE( DISTINCTCOUNT('Spotify Songs'[Track Name]), ALL('Spotify Songs'[Track Name]) ),
			    "-",
			    SELECTEDVALUE( 'Spotify Songs'[Artist Name] )
			)
		lineageTag: ca059252-00bf-4ee2-854a-e3a2b354b12f

	measure 'Select Release Date' =
			
			IF(
			    COUNT( 'Spotify Songs'[Track Name] ) = CALCULATE( DISTINCTCOUNT('Spotify Songs'[Track Name]), ALL('Spotify Songs'[Track Name]) ),
			    "-",
			    SELECTEDVALUE( 'Spotify Songs'[Release Date] )
			)
		formatString: Short Date
		lineageTag: c471fecb-bc5a-45aa-9b96-b52b4b63683e

	column 'Track Name'
		dataType: string
		lineageTag: d708e3c1-b371-4cdf-99a3-0ceccefe0fb7
		summarizeBy: none
		sourceColumn: Track Name

		annotation SummarizationSetBy = Automatic

	column 'Artist Name'
		dataType: string
		lineageTag: c5e8b036-3fa8-4f60-8005-8eff37de9096
		summarizeBy: none
		sourceColumn: Artist Name

		annotation SummarizationSetBy = Automatic

	column 'Artist Count'
		dataType: int64
		formatString: 0
		lineageTag: 5eb75ae7-6fe7-4d87-8999-080d5adc15c7
		summarizeBy: sum
		sourceColumn: Artist Count

		annotation SummarizationSetBy = Automatic

	column 'Released Year'
		dataType: int64
		formatString: 0
		lineageTag: 0cd87c0d-2513-49c3-ba77-638cd3675f07
		summarizeBy: none
		sourceColumn: Released Year

		annotation SummarizationSetBy = User

	column 'Released Month'
		dataType: int64
		formatString: 0
		lineageTag: 09bf0920-73ed-4360-8280-cafae5889820
		summarizeBy: none
		sourceColumn: Released Month

		annotation SummarizationSetBy = User

	column 'Released Day'
		dataType: int64
		formatString: 0
		lineageTag: edd50c78-d43c-4138-b028-c12b07cf5d0b
		summarizeBy: none
		sourceColumn: Released Day

		annotation SummarizationSetBy = User

	column 'In Spotify Playlists'
		dataType: int64
		formatString: 0
		lineageTag: 51e990de-5334-44bf-9932-b0f7085b32b6
		summarizeBy: sum
		sourceColumn: In Spotify Playlists

		annotation SummarizationSetBy = Automatic

	column 'In Spotify Charts'
		dataType: int64
		formatString: 0
		lineageTag: 5030eb41-3b7f-489b-9e56-0d3263018b00
		summarizeBy: sum
		sourceColumn: In Spotify Charts

		annotation SummarizationSetBy = Automatic

	column Streams
		dataType: int64
		formatString: #,0
		lineageTag: d46ddc55-23cd-4fdf-84b6-bfaabab023c3
		summarizeBy: sum
		sourceColumn: Streams

		annotation SummarizationSetBy = Automatic

	column 'In Apple Playlists'
		dataType: int64
		formatString: 0
		lineageTag: 6154dc66-bbca-4fdb-856c-1a7d2c9b2a65
		summarizeBy: sum
		sourceColumn: In Apple Playlists

		annotation SummarizationSetBy = Automatic

	column 'In Apple Charts'
		dataType: int64
		formatString: 0
		lineageTag: 5711dcce-1455-4568-9d97-6e608e332c3e
		summarizeBy: sum
		sourceColumn: In Apple Charts

		annotation SummarizationSetBy = Automatic

	column 'In Deezer Playlists'
		dataType: double
		lineageTag: fdfe02b7-cd20-407e-8d50-33fede327b5c
		summarizeBy: sum
		sourceColumn: In Deezer Playlists

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'In Deezer Charts'
		dataType: int64
		formatString: 0
		lineageTag: c132a708-0e8a-4505-9ad1-137b1a60d9bd
		summarizeBy: sum
		sourceColumn: In Deezer Charts

		annotation SummarizationSetBy = Automatic

	column 'In Shazam Charts'
		dataType: double
		lineageTag: b9a714e7-f9c9-4a30-8f9b-c00f169ac474
		summarizeBy: sum
		sourceColumn: In Shazam Charts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bpm
		dataType: int64
		formatString: #,0
		lineageTag: 20e354b7-2047-471a-bd54-acd5acd9e52b
		summarizeBy: sum
		sourceColumn: Bpm

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: c9a2c81c-61e6-49ff-8540-5f58f08df837
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Mode
		dataType: string
		lineageTag: f0b61766-ee78-465d-8613-a03521498b99
		summarizeBy: none
		sourceColumn: Mode

		annotation SummarizationSetBy = Automatic

	column 'Danceability %'
		dataType: double
		lineageTag: 1a88aa4f-a82e-40a0-85f9-c7e7f86fc85e
		summarizeBy: sum
		sourceColumn: Danceability %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Valence %'
		dataType: double
		lineageTag: dee6cfa8-62f1-4cbd-99c6-cc7151993dfb
		summarizeBy: sum
		sourceColumn: Valence %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Energy %'
		dataType: double
		lineageTag: 82f1d07b-c363-446d-b003-594a75cca6f8
		summarizeBy: sum
		sourceColumn: Energy %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Acousticness %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6f8832d6-cf6e-4cd2-9e91-08f3ec625c89
		summarizeBy: sum
		sourceColumn: Acousticness %

		annotation SummarizationSetBy = Automatic

	column 'Instrumentalness %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0254b6fa-356f-45dc-b078-58a8a6ebe169
		summarizeBy: sum
		sourceColumn: Instrumentalness %

		annotation SummarizationSetBy = Automatic

	column 'Liveness %'
		dataType: double
		lineageTag: dabef57e-6296-4c01-a1b2-e1192ba8b10f
		summarizeBy: sum
		sourceColumn: Liveness %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Speechiness %'
		dataType: double
		lineageTag: ac6f16b2-509d-4fec-a1f8-18cf1dc7363d
		summarizeBy: sum
		sourceColumn: Speechiness %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Release Date' =
			
			DATE(
			    'Spotify Songs'[Released Year],
			    'Spotify Songs'[Released Month],
			    'Spotify Songs'[Released Day]
			)
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4a88be76-91cb-4039-a2e7-a378af6be2a1
		summarizeBy: none
		isDataTypeInferred

		variation Variation
			isDefault
			relationship: 2ba1ffb3-9813-42d2-b8fa-d69ba1ec456b
			defaultHierarchy: LocalDateTable_3faa6600-61c9-4eb9-b230-d5870a878415.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	hierarchy 'Released Date Hierarchy'
		lineageTag: 996f9997-b1e7-4bff-9f3c-b3b7591b2488

		level 'Released Year'
			lineageTag: 56853a10-854f-4165-b4f3-0eabf8d85675
			column: 'Released Year'

		level 'Released Month'
			lineageTag: 50fcccaa-56bf-4e17-b810-a35491a4451f
			column: 'Released Month'

		level 'Released Day'
			lineageTag: f7c8d8dc-e1d2-4903-bfcc-16bca4f745f5
			column: 'Released Day'

	partition 'Spotify Songs' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-0-eu-central-1.pooler.supabase.com", "postgres"),
				    public_kaggle_popular_spotify_songs = Source{[Schema="public",Item="kaggle_popular_spotify_songs"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_kaggle_popular_spotify_songs,{{"track_name", type text}, {"artist_name", type text}, {"artist_count", Int64.Type}, {"released_year", Int64.Type}, {"released_month", Int64.Type}, {"released_day", Int64.Type}, {"in_spotify_playlists", Int64.Type}, {"in_spotify_charts", Int64.Type}, {"streams", Int64.Type}, {"in_apple_playlists", Int64.Type}, {"in_apple_charts", Int64.Type}, {"in_deezer_playlists", type number}, {"in_deezer_charts", Int64.Type}, {"in_shazam_charts", type number}, {"bpm", Int64.Type}, {"key", type text}, {"mode", type text}, {"danceability_%", type number}, {"valence_%", type number}, {"energy_%", type number}, {"acousticness_%", type number}, {"instrumentalness_%", type number}, {"liveness_%", type number}, {"speechiness_%", type number}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"streams", null}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Errors",{{"track_name", "Track Name"}, {"artist_name", "Artist Name"}, {"artist_count", "Artist Count"}, {"released_year", "Released Year"}, {"released_month", "Released Month"}, {"released_day", "Released Day"}, {"in_spotify_playlists", "In Spotify Playlists"}, {"in_spotify_charts", "In Spotify Charts"}, {"streams", "Streams"}, {"in_apple_playlists", "In Apple Playlists"}, {"in_apple_charts", "In Apple Charts"}, {"in_deezer_playlists", "In Deezer Playlists"}, {"in_deezer_charts", "In Deezer Charts"}, {"in_shazam_charts", "In Shazam Charts"}, {"bpm", "Bpm"}, {"key", "Key"}, {"mode", "Mode"}, {"danceability_%", "Danceability %"}, {"valence_%", "Valence %"}, {"energy_%", "Energy %"}, {"acousticness_%", "Acousticness %"}, {"instrumentalness_%", "Instrumentalness %"}, {"liveness_%", "Liveness %"}, {"speechiness_%", "Speechiness %"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

